name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Verify Go Modules
        run: go mod tidy && git diff --exit-code || { echo "Run 'go mod tidy' and commit changes"; exit 1; }

      - name: Run Tests
        run: go test -v ./...

